#!/bin/sh

# `make maintainer-clean` will remove any file created by the ./configure.
if [ -f Makefile ]; then
    make maintainer-clean
fi
# But it does not clean out files created by ./autogen.sh. This script does this.
rm -f aclocal.m4 config.guess config.sub configure depcomp install-sh ltmain.sh Makefile.in missing py-compile
# This is a cache generated by the autotools to accelerate file generation. It can be safely removed.
rm -fr autom4te.cache/

# The next line removes the archive created by `make dist`.
rm -f compact-language-detector-*.tar.gz
