Document: compact-language-detector
Title: Debian compact-language-detector Manual
Author: <insert document author here>
Abstract: This manual describes what compact-language-detector is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/compact-language-detector/compact-language-detector.sgml.gz

Format: postscript
Files: /usr/share/doc/compact-language-detector/compact-language-detector.ps.gz

Format: text
Files: /usr/share/doc/compact-language-detector/compact-language-detector.text.gz

Format: HTML
Index: /usr/share/doc/compact-language-detector/html/index.html
Files: /usr/share/doc/compact-language-detector/html/*.html
